
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'NUMBER PRINTexpression : pyramidpyramid : NUMBERpyramid : pyramid NUMBERpyramid : pyramid PRINT'
    
_lr_action_items = {'NUMBER':([0,2,3,4,5,],[3,4,-2,-3,-4,]),'$end':([1,2,3,4,5,],[0,-1,-2,-3,-4,]),'PRINT':([2,3,4,5,],[5,-2,-3,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,],[1,]),'pyramid':([0,],[2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> pyramid','expression',1,'p_expression_pyramid','pyramid_lex.py',31),
  ('pyramid -> NUMBER','pyramid',1,'p_pyramid_number','pyramid_lex.py',36),
  ('pyramid -> pyramid NUMBER','pyramid',2,'p_pyramid_pyramid_number','pyramid_lex.py',41),
  ('pyramid -> pyramid PRINT','pyramid',2,'p_intermediate_print','pyramid_lex.py',47),
]
